language: node_js
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
  - windows
node_js:
  - '10'
  - '9'
  - '8'
  - '7'
  - '6'
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
        - CC="gcc-4.9"
        - CXX="g++-4.9"
install:
  - npm install
script:
  - npm test
